### PR TITLE
Compatibility section in the readme

### PR DESCRIPTION
**Pull request by michielbdejong**
Referring to RFC versions by commit hash is a bit funny, but I guess it's good enough.

### CODE REVIEW

**Comment by emschwartz** [comment]
These commits should be squashed and should follow the commitizen format

**Comment by michielbdejong** [comment]
Hah, using github's online editor interface let me bypass the commit hook :)
Yeah, I was going to squash them, just hadn't done it yet.

@emschwartz done.

**Review by emschwartz — APPROVED** [review]
We should probably start versioning the ledger plugin interface, but this LGTM for now

**Comment by michielbdejong** [comment]
Hm, tests failed with `Error: Cannot find module 'five-bells-service-manager'`

**Comment by michielbdejong** [comment]
Rebuilding circleci without cache

**Pull request merged**
